#!/bin/sh -eu

# For protobuf
buf lint
buf format --diff --exit-code
buf generate

# For Rust
cargo_toml_path=$(find . -name 'Cargo.toml')
cargo clippy --manifest-path "$cargo_toml_path" --bins --tests --examples --all -- -D warnings
cargo fmt --manifest-path "$cargo_toml_path" --check
