name: Check PR
on:
  pull_request:
    types: [synchronize, opened, ready_for_review]
    branches: ["main"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-lint-protobuf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
  check-lint-protobuf-breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main'
  check-lint-rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gen/rust
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.17.2
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Check Rust lint
        run: cargo clippy --bins --tests --examples --all -- -D warnings
  check-lint:
    runs-on: ubuntu-latest
    needs: [check-lint-protobuf, check-lint-protobuf-breaking, check-lint-rust]
    if: failure()
    steps:
      - run: exit 1

  check-format-protobuf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - name: Check Protobuf format
        run: buf format --diff --exit-code
  check-format-rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gen/rust
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check Rust format
        run: cargo fmt --check
  check-format:
    runs-on: ubuntu-latest
    needs: [check-format-protobuf, check-format-rust]
    if: failure()
    steps:
      - run: exit 1

  check-status:
    runs-on: ubuntu-latest
    needs: [check-lint, check-format]
    if: failure()
    steps:
      - run: exit 1
