name: check rust code
on: pull_request
jobs:
  check-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: arduino/setup-protoc@v1
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo clippy
        run: |
          cargo_toml_path=$(find . -name 'Cargo.toml')
          cargo clippy --manifest-path "$cargo_toml_path" --bins --tests --examples --all -- -D warnings
      - name: Commit, add and push codes
        run: |
          cargo_toml_path=$(find . -name 'Cargo.toml')
          cargo fmt --manifest-path "$cargo_toml_path"
          if git diff --exit-code --quiet; then
            exit 0
          fi
          git config user.name 'github-actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Run rustfmt"
          git push origin @
      - name: Compile packages
        run: |
          cargo_toml_path=$(find . -name 'Cargo.toml')
          cargo build --manifest-path "$cargo_toml_path"
