name: check protobuf
on: pull_request
jobs:
  check-buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: arduino/setup-protoc@v1
      - name: Install go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - name: Format all protobuf files
        run: |
          buf format --write
          if git diff --exit-code --quiet; then
            exit 0
          fi
          git config user.name 'github-actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Run buf format"
          git push origin @
      - name: Generate code from all protobuf files
        run: |
          buf generate
          if git diff --exit-code --quiet; then
            exit 0
          fi
          git config user.name 'github-actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Run buf generate"
          git push origin @
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main'
