name: workflow-for-pull-request
on: pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: arduino/setup-protoc@v1
      - name: Install go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - name: Format all Protobuf files
        run: buf format --write
      - name: Generate code from all Protobuf files
        run: buf generate
      - name: Commit, add and push all diff files
        run: |
          if git diff --exit-code --quiet; then
            exit 0
          fi
          git config user.name 'github-actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Run Rustfmt"
          git push origin @
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main'
